//
// Created by Aurel Gruber on 13.09.17.
//

#ifndef GEOMETRYPROCESSINGPIPELINE_MACROS_H
#define GEOMETRYPROCESSINGPIPELINE_MACROS_H


#define GEOMETRY_PROCESSING_PIPELINE_NAMESPACE_START \
namespace GPP {

#define GEOMETRY_PROCESSING_PIPELINE_NAMESPACE_END \
} // GPP

#endif //GEOMETRYPROCESSINGPIPELINE_MACROS_H
